### ISSUE TITLE
Doesn't set blank values

### ISSUE THREAD

**Issue by scriptmaster** [sleeuwen/dotnet-json#4]
Thanks for this tool. It is a great (dotnet-native) alternative than `jq` or `Octopus Deploy` for CICD.

Sometimes you want to configure a key to be blank (string.Empty). The tool doesn't allow to set in these scenarios.  It would be good if you could take care of this also.

`
dotnet json set appsettings.json MyKeyGroup:KeyName ""
`

**Comment by sleeuwen** [comment]
Hi! Thanks for you issue, I wasn't aware of the fact this isn't allowed but it does definitely make sense to allow it.

After further investigation it was actually an issue of the System.CommandLine package that I'm using, which luckily has already been fixed in a newer version. I've updated the dependency and can now successfully set a key to a blank value. To be sure I've also added a unit test that verifies it will work in the future.

I've published version 1.0.2 with this fix, can you try that version for yourself and see if it's working correctly?

**Comment by sleeuwen** [comment]
Closing this for now as the new version should fix it, feel free to reopen this issue if it doesn't work for you
